### ISSUE TITLE
fix(form): develop per form currency snippet

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Snippet-Library#72]
We already have a basic snippet: https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-per-form-currency.php

Note: Do not care about the report, earning and goal calculation with different currencies, but this snippet main goal to perform donation with currency other than base currency.

### ToDo:
- [ ] <s>Add form setting to choose a currency</s>.
- [x] Add logic to perform donation with form currency if set any.

### Tests:
- [x] Check this functionality with page which has multiple forms with multiple currencies.
- [x] Check this functionality with multi and set donation form.
- [x] Check amount formating for form currency on following places:
   - [x] Single form page
   - [x] Donation list and donation detail page
  - [x] Donaiton log listing
- [x] Donation listing page and donation detail page must show form currency if any.
- [x] Check donation log

**Comment by Sidsector9** [comment]
I have tested the above tasks with [this](https://github.com/WordImpress/Give-Snippet-Library/pull/76) PR.

1. Page with multiple forms with multiple currencies work as expected. Currencies are shown correctly.
2. Form of type Set and Multi both work correctly. Currency is shown correctly.
3. Donation listing page, donation details page and the logs all three show correct currency and value.

CC: @ravinderk
